import { WatchlistPair, Rule, Trade } from "./types";

export const defaultPairs: WatchlistPair[] = [
  { id: "eurusd", symbol: "EUR/USD", active: true, custom: false },
  { id: "gbpusd", symbol: "GBP/USD", active: true, custom: false },
  { id: "gbpjpy", symbol: "GBP/JPY", active: true, custom: false },
];

export const defaultRules: Rule[] = [
  { id: "basis-1", label: "Daily orderflow DOLR", category: "BASIS", checked: false },
  { id: "basis-2", label: "Daily orderflow ICR ×", category: "BASIS", checked: false },
  { id: "basis-3", label: "4H orderflow + POI ×", category: "BASIS", checked: false },
  { id: "basis-4", label: "4H orderflow + CRT ×", category: "BASIS", checked: false },
  { id: "entry-1", label: "Reversal — orderflow", category: "ENTRY", checked: false },
  { id: "entry-2", label: "15M orderflow + POI", category: "ENTRY", checked: false },
  { id: "entry-3", label: "15M orderflow + Sweep", category: "ENTRY", checked: false },
  { id: "entry-4", label: "5M orderflow + POI", category: "ENTRY", checked: false },
  { id: "entry-5", label: "5M orderflow BMS", category: "ENTRY", checked: false },
];

export const sampleTrades: Trade[] = [
  {
    id: "t1",
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    session: "LONDON",
    pair: "EUR/USD",
    bias: "BULLISH",
    psychology: ["CALM"],
    rulesChecked: ["basis-1", "basis-3", "entry-1", "entry-2"],
    totalRules: 9,
    checkedCount: 4,
    missingRules: ["basis-2", "basis-4", "entry-3", "entry-4", "entry-5"],
    decision: "TAKE",
    outcome: "WIN",
    accountBalance: 10000,
    riskPercent: 1,
    riskAmount: 100,
    stopLossPips: 15,
    lotSize: 0.67,
    rr: 2.5,
    pnl: 250,
    notes: "Clean setup, good entry on retrace",
  },
  {
    id: "t2",
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    session: "NEW_YORK",
    pair: "GBP/USD",
    bias: "BEARISH",
    psychology: ["FOMO"],
    rulesChecked: ["basis-1", "entry-1"],
    totalRules: 9,
    checkedCount: 2,
    missingRules: ["basis-2", "basis-3", "basis-4", "entry-2", "entry-3", "entry-4", "entry-5"],
    decision: "TAKE",
    outcome: "LOSS",
    accountBalance: 10250,
    riskPercent: 1.5,
    riskAmount: 153.75,
    stopLossPips: 20,
    lotSize: 0.77,
    rr: 1.5,
    pnl: -153.75,
    notes: "Forced trade, didn't wait for confirmation",
  },
  {
    id: "t3",
    date: new Date().toISOString().split("T")[0],
    session: "LONDON",
    pair: "GBP/JPY",
    bias: "BULLISH",
    psychology: ["CALM"],
    rulesChecked: [],
    totalRules: 9,
    checkedCount: 0,
    missingRules: ["basis-1","basis-2","basis-3","basis-4","entry-1","entry-2","entry-3","entry-4","entry-5"],
    decision: "SKIP",
    accountBalance: 10096.25,
    riskPercent: 1,
    riskAmount: 100.96,
    stopLossPips: 0,
    lotSize: 0,
    rr: 0,
    notes: "Setup not clean enough",
  },
];
